# -*- coding: utf-8 -*-
"""текстовые.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SzS64mX7yyMVeLRruZFc-p0ncxRW4QZV
"""

# =========================================================================================
# Курсовой проект: поиск и первичный анализ наборов данных по различным областям применения
# Кейс: Классификация спама по тексту электронного письма
# Выполнила: Палеева Виктория Станиславовна, группа ЕТ-142
# Дата: 15.05.2026
# =========================================================================================
import pandas as pd
import numpy as np

df = pd.read_csv('/content/spam.csv', encoding='latin-1', sep=',', on_bad_lines='skip')

print("\n" + "="*60)
print("ИНФОРМАЦИЯ О ДАТАСЕТЕ")
print("="*60)
print(f"Размер датасета (до обработки): {df.shape[0]} строк, {df.shape[1]} столбцов")
print(f"\nНазвания столбцов: {list(df.columns)}")

# ==================== ПЕРВИЧНЫЙ АНАЛИЗ ПРОПУСКОВ ====================
print("\n" + "="*60)
print("ПЕРВИЧНЫЙ АНАЛИЗ ПРОПУСКОВ (ДО УДАЛЕНИЯ)")
print("="*60)
print("\nКоличество пропусков в каждом столбце:")
print(df.isnull().sum())

# ==================== ШАГ 1: УДАЛЕНИЕ СТРОК, ГДЕ ЕСТЬ ЗНАЧЕНИЯ В UNNAMED СТОЛБЦАХ ====================
print("\n" + "="*60)
print("ШАГ 1: УДАЛЕНИЕ СТРОК СО ЗНАЧЕНИЯМИ В UNNAMED СТОЛБЦАХ")
print("="*60)

# Находим все столбцы, которые начинаются с 'Unnamed'
unnamed_cols = [col for col in df.columns if col.startswith('Unnamed')]
print(f"Найдены столбцы Unnamed: {unnamed_cols}")

if unnamed_cols:
    # Считаем строки, где есть хотя бы одно непустое значение в любом из Unnamed столбцов
    rows_with_unnamed = df[unnamed_cols].notna().any(axis=1)
    unnamed_rows_count = rows_with_unnamed.sum()

    print(f"Количество строк со значениями в Unnamed столбцах: {unnamed_rows_count}")

    # Показываем примеры таких строк
    if unnamed_rows_count > 0:
        print("\nПримеры строк со значениями в Unnamed столбцах:")
        examples = df[rows_with_unnamed].head(3)
        for idx, row in examples.iterrows():
            print(f"\nСтрока {idx}:")
            print(f"  label (v1): {row.iloc[0]}")
            print(f"  message (v2): {str(row.iloc[1])[:100]}...")
            for col in unnamed_cols:
                if pd.notna(row[col]):
                    print(f"  {col}: {row[col]}")

    # Удаляем строки с любыми значениями в Unnamed столбцах
    df = df[~rows_with_unnamed]
    print(f"\nУдалено строк с данными в Unnamed столбцах: {unnamed_rows_count}")
    print(f"Осталось строк после удаления: {df.shape[0]}")
else:
    print("Столбцы Unnamed не найдены")

# ==================== ШАГ 2: УДАЛЕНИЕ ПУСТЫХ СТОЛБЦОВ ====================
print("\n" + "="*60)
print("ШАГ 2: УДАЛЕНИЕ ПУСТЫХ СТОЛБЦОВ")
print("="*60)

# Запоминаем какие столбцы были удалены
cols_before = df.shape[1]
empty_cols = df.columns[df.isnull().all()].tolist()
print(f"Полностью пустые столбцы: {empty_cols}")

df = df.dropna(axis=1, how='all')
cols_after = df.shape[1]
print(f"Удалено полностью пустых столбцов: {cols_before - cols_after}")
print(f"Оставшиеся столбцы: {list(df.columns)}")

# ==================== ШАГ 3: УДАЛЕНИЕ ПУСТЫХ СТРОК ====================
print("\n" + "="*60)
print("ШАГ 3: УДАЛЕНИЕ ПУСТЫХ СТРОК")
print("="*60)

rows_before = df.shape[0]
empty_rows_count = df.isnull().all(axis=1).sum()
print(f"Количество полностью пустых строк: {empty_rows_count}")

df = df.dropna(axis=0, how='all')
rows_after = df.shape[0]
print(f"Удалено полностью пустых строк: {rows_before - rows_after}")

# ==================== ШАГ 4: ОСТАВЛЯЕМ ТОЛЬКО ПЕРВЫЕ ДВА СТОЛБЦА ====================
print("\n" + "="*60)
print("ШАГ 4: ОСТАВЛЯЕМ ТОЛЬКО ПЕРВЫЕ ДВА СТОЛБЦА")
print("="*60)

if len(df.columns) >= 2:
    # Берем первые два столбца (независимо от их названий)
    df = df.iloc[:, :2]
    # Переименовываем столбцы для удобства
    df.columns = ['label', 'message']
    print(f"Оставлены столбцы: label (тип сообщения), message (текст сообщения)")
else:
    print("В датасете меньше 2 столбцов!")

# ==================== ШАГ 5: ИТОГОВАЯ ПРОВЕРКА НА ПРОПУСКИ ====================
print("\n" + "="*60)
print("ИТОГОВАЯ ПРОВЕРКА НА ПРОПУСКИ")
print("="*60)
print(f"Текущий размер датасета: {df.shape[0]} строк, {df.shape[1]} столбца")
print(f"\nКоличество пропусков в оставшихся столбцах:")
print(df.isnull().sum())

total_nulls = df.isnull().sum().sum()
if total_nulls > 0:
    print(f"\nВсего пропусков в датасете: {total_nulls}")
    print(f"Процент пропусков: {(total_nulls / (df.shape[0] * df.shape[1]) * 100):.2f}%")

    # Удаляем оставшиеся строки с пропусками
    df = df.dropna()
    print(f"\nУдалены строки с пропусками. Осталось строк: {df.shape[0]}")
else:
    print("Пропусков в датасете нет!")

# ==================== ФИНАЛЬНАЯ СТАТИСТИКА ====================
print("\n" + "="*60)
print("ФИНАЛЬНАЯ СТАТИСТИКА ПОСЛЕ ВСЕХ ОЧИСТОК")
print("="*60)
print(f"Итоговый размер датасета: {df.shape[0]} строк, {df.shape[1]} столбца")
print(f"Пропусков после всех очисток: {df.isnull().sum().sum()}")

# Сохраняем результат в новый файл (просто сохраняем, не скачиваем)
output_filename = "spam_cleaned.csv"
df.to_csv(output_filename, index=False, encoding='utf-8')
print(f"\nФайл сохранен в Colab как: {output_filename}")
print(f"Полный путь: /content/{output_filename}")

# ==================== ДЕМОНСТРАЦИЯ РЕЗУЛЬТАТОВ ====================
# Статистика по типам сообщений
print("\n" + "="*60)
print("СТАТИСТИКА ПО ТИПАМ СООБЩЕНИЙ")
print("="*60)
if 'label' in df.columns:
    print(f"\nРаспределение по типам:")
    print(df['label'].value_counts())
    print(f"\nПроцент спама: {(df['label'] == 'spam').mean() * 100:.2f}%")
    print(f"Процент ham: {(df['label'] == 'ham').mean() * 100:.2f}%")
print("\n" + "="*60)
print("ОБРАБОТКА ЗАВЕРШЕНА УСПЕШНО!")
print("="*60)

import pandas as pd
import re

# 1. Загрузка очищенного от пропусков датасета
df = pd.read_csv('/content/spam_cleaned.csv', encoding='latin-1')

print("="*60)
print("ЗАГРУЗКА ДАННЫХ")
print("="*60)
print(f"Размер датасета: {df.shape[0]} строк, {df.shape[1]} столбцов")
print(f"Колонки: {df.columns.tolist()}")

# 2. Определяем нужные колонки (метка и текст)
label_col = None
text_col = None

for col in df.columns:
    if 'v1' in col or 'label' in col.lower():
        label_col = col
    if 'v2' in col or 'message' in col.lower() or 'text' in col.lower():
        text_col = col

print(f"\nНайдена колонка с метками: '{label_col}'")
print(f"Найдена колонка с текстом: '{text_col}'")

if label_col and text_col:
    df = df[[label_col, text_col]]
    df.columns = ['label', 'text']

    # ==================== УДАЛЕНИЕ PII ====================
    print("\n" + "="*60)
    print("УДАЛЕНИЕ ПЕРСОНАЛЬНЫХ ДАННЫХ (PII)")
    print("="*60)

    def remove_pii(text):
        """Удаляет персональные данные из текста (email, телефоны, URL, паспорта)"""
        text = str(text)

        # 1. Удаление email-адресов
        text = re.sub(r'\S+@\S+\.\S+', '', text, flags=re.IGNORECASE)
        text = re.sub(r'[\w\.-]+@[\w\.-]+\.\w+', '', text, flags=re.IGNORECASE)

        # 2. Удаление номеров телефонов (различные форматы)
        # Международные форматы: +7, +1, +44 и т.д.
        text = re.sub(r'\+\d{1,3}[-.\s]?\(?\d{1,4}\)?[-.\s]?\d{1,5}[-.\s]?\d{1,5}[-.\s]?\d{1,5}', '', text)
        # Номера без кода страны: 8XXXXXXXXX, 10-11 цифр
        text = re.sub(r'\b\d{10,11}\b', '', text)
        # Номера с разделителями: 123-456-7890, 123.456.7890, (123) 456-7890
        text = re.sub(r'\(?\d{3}\)?[-.\s]?\d{3}[-.\s]?\d{4}\b', '', text)
        # Британские короткие номера: 0800 123 4567, 0906 123 4567
        text = re.sub(r'\b0[0-9]{3}[-.\s]?[0-9]{3}[-.\s]?[0-9]{4}\b', '', text)

        # 4. Удаление номеров паспортов и документов
        # Российский паспорт: 2 цифры, пробел, 2 цифры, пробел, 6 цифр (пример: 45 12 345678)
        text = re.sub(r'\b\d{2}[-.\s]?\d{2}[-.\s]?\d{6}\b', '', text)
        # Загранпаспорт: 2 цифры, 7 цифр (пример: 451234567)
        text = re.sub(r'\b\d{2}[-.\s]?\d{7}\b', '', text)
        # Паспорт с серией и номером в одном блоке (10 цифр подряд)
        text = re.sub(r'\b\d{10}\b', '', text)
        # Паспорт с буквами: например, AB123456 (латинские буквы + цифры)
        text = re.sub(r'\b[A-Z]{2}\d{6}\b', '', text, flags=re.IGNORECASE)
        text = re.sub(r'\b[A-Z]{2}[-.\s]?\d{6}\b', '', text, flags=re.IGNORECASE)

        # 5. Удаление лишних пробелов (которые могли появиться после удаления)
        text = re.sub(r'\s+', ' ', text)  # Множественные пробелы -> один пробел
        text = text.strip()               # Пробелы в начале и конце

        return text

    # Применяем удаление PII ко всем текстам
    print("\nУдаление персональных данных...")
    df['text_cleaned'] = df['text'].apply(remove_pii)

    # Показываем примеры ДО и ПОСЛЕ удаления PII
    print("\n" + "="*60)
    print("ПРИМЕРЫ УДАЛЕНИЯ PII")
    print("="*60)

    shown = 0
    for i in range(len(df)):
        # Ищем строки, где есть изменения
        if df['text'].iloc[i] != df['text_cleaned'].iloc[i] and shown < 3:
            print(f"\n--- Пример {shown+1} ---")
            print(f"ДО:    {df['text'].iloc[i][:200]}")
            print(f"ПОСЛЕ: {df['text_cleaned'].iloc[i][:200]}")
            shown += 1

    if shown == 0:
        print("\nPII данные не найдены в первых строках (это хорошо)")

    # Подсчитываем статистику удалений
    print("\n" + "="*60)
    print("СТАТИСТИКА УДАЛЕНИЯ PII")
    print("="*60)

    # Считаем, сколько сообщений содержали различные типы PII
    email_count = df['text'].str.contains(r'\S+@\S+\.\S+', na=False, regex=True).sum()
    phone_count = df['text'].str.contains(r'\b\d{10,11}\b|\(\d{3}\)\s?\d{3}-\d{4}', na=False, regex=True).sum()
    passport_count = df['text'].str.contains(r'\b\d{2}\s?\d{2}\s?\d{6}\b|\b\d{10}\b', na=False, regex=True).sum()

    print(f"Сообщений с email: {email_count}")
    print(f"Сообщений с номерами телефонов: {phone_count}")
    print(f"Сообщений с номерами паспортов: {passport_count}")

    # 4. Заменяем исходный текст на очищенный (без PII)
    df['text'] = df['text_cleaned']
    df = df.drop(columns=['text_cleaned'])

    # 7. Статистика
    print("\n" + "="*60)
    print("ФИНАЛЬНАЯ СТАТИСТИКА")
    print("="*60)
    print(f"Всего сообщений: {len(df)}")
    print(f"Средняя длина текста: {df['text'].str.len().mean():.1f} символов")
    print(f"\nРаспределение классов:")
    print(df['label'].value_counts())

    # 8. Сохраняем в новый CSV-файл
    output_filename = 'spam_pii_removed.csv'
    df.to_csv(output_filename, index=False, encoding='utf-8')
    print(f"\nФайл сохранен в Colab как: '{output_filename}'")
    print(f"Полный путь: /content/{output_filename}")
else:
    print("\nНе удалось найти нужные колонки. В файле есть только:")
    print(df.columns.tolist())

print("\n" + "="*60)
print("ОБРАБОТКА ЗАВЕРШЕНА УСПЕШНО!")
print("="*60)

import matplotlib.pyplot as plt
from sklearn.utils import resample

# 1. Загрузка данных
df = pd.read_csv('/content/spam_pii_removed.csv', encoding='utf-8')

print("="*60)
print("ЗАГРУЗКА ДАННЫХ")
print("="*60)
print(f"Размер датасета: {df.shape[0]} строк, {df.shape[1]} столбцов")
print(f"Колонки: {df.columns.tolist()}")

# Проверяем, есть ли колонка 'label'
if 'label' not in df.columns:
    print("Колонка 'label' не найдена!")
    print(f"Доступные колонки: {df.columns.tolist()}")
    exit()

# ==================== ДИАГРАММА 1: ДО БАЛАНСИРОВКИ ====================
print("\n" + "="*60)
print("ДИАГРАММА 1: РАСПРЕДЕЛЕНИЕ КЛАССОВ ДО БАЛАНСИРОВКИ")
print("="*60)

class_counts_before = df['label'].value_counts()
print(f"\nРаспределение до балансировки:")
print(class_counts_before)
print(f"\nПроцент спама: {(df['label'] == 'spam').mean() * 100:.2f}%")
print(f"Процент ham: {(df['label'] == 'ham').mean() * 100:.2f}%")

# Строим столбчатую диаграмму
fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# Столбчатая диаграмма
colors_before = ['#ff6b6b' if label == 'spam' else '#4ecdc4' for label in class_counts_before.index]
axes[0].bar(class_counts_before.index, class_counts_before.values, color=colors_before, edgecolor='black')
axes[0].set_title('Распределение классов ДО балансировки', fontsize=14, fontweight='bold')
axes[0].set_xlabel('Класс', fontsize=12)
axes[0].set_ylabel('Количество сообщений', fontsize=12)
axes[0].grid(axis='y', alpha=0.3)

# Добавляем значения на столбцы
for i, (label, count) in enumerate(class_counts_before.items()):
    axes[0].text(i, count + 50, str(count), ha='center', fontsize=12, fontweight='bold')

# Круговая диаграмма
axes[1].pie(class_counts_before.values, labels=class_counts_before.index, autopct='%1.1f%%',
            colors=['#ff6b6b', '#4ecdc4'], startangle=90, explode=(0.05, 0))
axes[1].set_title('Соотношение классов ДО балансировки', fontsize=14, fontweight='bold')

plt.tight_layout()
plt.savefig('/content/balance_before.png', dpi=150, bbox_inches='tight')
print("\nДиаграмма 'ДО' сохранена как: balance_before.png")

# ==================== БАЛАНСИРОВКА КЛАССОВ ====================
print("\n" + "="*60)
print("БАЛАНСИРОВКА КЛАССОВ")
print("="*60)

# Разделяем классы
df_spam = df[df['label'] == 'spam']
df_ham = df[df['label'] == 'ham']

print(f"\nДо балансировки:")
print(f"  Спам: {len(df_spam)} сообщений")
print(f"  Ham:  {len(df_ham)} сообщений")

# Определяем целевое количество (минимальный класс - спам)
target_count = len(df_spam)
print(f"\nЦелевое количество: {target_count} сообщений (по минимуму - спам)")

# Уменьшаем класс ham до размера spam (даунсемплинг)
df_ham_balanced = resample(df_ham,
                           replace=False,           # без повторений
                           n_samples=target_count,  # столько же, сколько спама
                           random_state=42)         # для воспроизводимости

# Собираем сбалансированный датасет
df_balanced = pd.concat([df_spam, df_ham_balanced])

# Перемешиваем строки
df_balanced = df_balanced.sample(frac=1, random_state=42).reset_index(drop=True)

print(f"\nПосле балансировки (даунсемплинг):")
print(f"  Спам: {len(df_balanced[df_balanced['label'] == 'spam'])} сообщений")
print(f"  Ham:  {len(df_balanced[df_balanced['label'] == 'ham'])} сообщений")
print(f"  Всего: {len(df_balanced)} сообщений")

# ==================== ДИАГРАММА 2: ПОСЛЕ БАЛАНСИРОВКИ ====================
print("\n" + "="*60)
print("ДИАГРАММА 2: РАСПРЕДЕЛЕНИЕ КЛАССОВ ПОСЛЕ БАЛАНСИРОВКИ")
print("="*60)

class_counts_after = df_balanced['label'].value_counts()
print(f"\nРаспределение после балансировки:")
print(class_counts_after)
print(f"\nПроцент спама: {(df_balanced['label'] == 'spam').mean() * 100:.2f}%")
print(f"Процент ham: {(df_balanced['label'] == 'ham').mean() * 100:.2f}%")

# Строим столбчатую диаграмму
fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# Столбчатая диаграмма
colors_after = ['#ff6b6b' if label == 'spam' else '#4ecdc4' for label in class_counts_after.index]
axes[0].bar(class_counts_after.index, class_counts_after.values, color=colors_after, edgecolor='black')
axes[0].set_title('Распределение классов ПОСЛЕ балансировки', fontsize=14, fontweight='bold')
axes[0].set_xlabel('Класс', fontsize=12)
axes[0].set_ylabel('Количество сообщений', fontsize=12)
axes[0].grid(axis='y', alpha=0.3)

# Добавляем значения на столбцы
for i, (label, count) in enumerate(class_counts_after.items()):
    axes[0].text(i, count + 5, str(count), ha='center', fontsize=12, fontweight='bold')

# Круговая диаграмма
axes[1].pie(class_counts_after.values, labels=class_counts_after.index, autopct='%1.1f%%',
            colors=['#ff6b6b', '#4ecdc4'], startangle=90)
axes[1].set_title('Соотношение классов ПОСЛЕ балансировки', fontsize=14, fontweight='bold')

plt.tight_layout()
plt.savefig('/content/balance_after.png', dpi=150, bbox_inches='tight')
print("\nДиаграмма 'ПОСЛЕ' сохранена как: balance_after.png")

# ==================== СОХРАНЕНИЕ СБАЛАНСИРОВАННОГО ФАЙЛА ====================
print("\n" + "="*60)
print("СОХРАНЕНИЕ РЕЗУЛЬТАТОВ")
print("="*60)

output_filename = 'spam_balanced.csv'
df_balanced.to_csv(output_filename, index=False, encoding='utf-8')
print(f"\nСбалансированный датасет сохранен как: '{output_filename}'")
print(f"Полный путь: /content/{output_filename}")

# ==================== ФИНАЛЬНАЯ СТАТИСТИКА ====================
print("\n" + "="*60)
print("ФИНАЛЬНАЯ СТАТИСТИКА")
print("="*60)
print(f"Исходный размер: {len(df)} сообщений")
print(f"Сбалансированный размер: {len(df_balanced)} сообщений")
print(f"Удалено сообщений (ham): {len(df_ham) - target_count}")
print(f"\nИтоговое распределение:")
print(df_balanced['label'].value_counts())

# Показываем примеры после балансировки
print("\n" + "="*60)
print("ПРИМЕРЫ СООБЩЕНИЙ ПОСЛЕ БАЛАНСИРОВКИ")
print("="*60)

print("\n--- Спам (первые 2 примера) ---")
spam_samples = df_balanced[df_balanced['label'] == 'spam']['text'].head(2)
for i, msg in enumerate(spam_samples, 1):
    print(f"{i}. {msg[:100]}...")

print("\n--- Ham (первые 2 примера) ---")
ham_samples = df_balanced[df_balanced['label'] == 'ham']['text'].head(2)
for i, msg in enumerate(ham_samples, 1):
    print(f"{i}. {msg[:100]}...")

print("\n" + "="*60)
print("ОБРАБОТКА ЗАВЕРШЕНА УСПЕШНО!")
print("="*60)

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# 1. Загружаем данные
df = pd.read_csv('/content/spam_balanced.csv', encoding='utf-8')

print("="*60)
print("ГИСТОГРАММА РАСПРЕДЕЛЕНИЯ ДЛИН СООБЩЕНИЙ")
print("="*60)

# 2. Вычисляем длины сообщений (в символах)
df['text_length'] = df['text'].astype(str).str.len()

# 3. Основная статистика
print(f"\nСтатистика длин сообщений:")
print(f"  Минимальная длина: {df['text_length'].min()} символов")
print(f"  Максимальная длина: {df['text_length'].max()} символов")
print(f"  Средняя длина: {df['text_length'].mean():.1f} символов")
print(f"  Медианная длина: {df['text_length'].median():.1f} символов")
print(f"  Стандартное отклонение: {df['text_length'].std():.1f}")

# 4. Отдельно для спама и ham
print(f"\nСтатистика по классам:")
for label in ['spam', 'ham']:
    lengths = df[df['label'] == label]['text_length']
    print(f"\n  {label}:")
    print(f"    Средняя: {lengths.mean():.1f} символов")
    print(f"    Медиана: {lengths.median():.1f} символов")
    print(f"    Максимум: {lengths.max()} символов")

# 5. Строим гистограмму
fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# Гистограмма 1: общее распределение
axes[0].hist(df['text_length'], bins=30, color='skyblue', edgecolor='black', alpha=0.7)
axes[0].axvline(df['text_length'].mean(), color='red', linestyle='--', linewidth=2, label=f'Среднее = {df["text_length"].mean():.1f}')
axes[0].axvline(df['text_length'].median(), color='green', linestyle='--', linewidth=2, label=f'Медиана = {df["text_length"].median():.1f}')
axes[0].set_xlabel('Длина сообщения (символы)', fontsize=12)
axes[0].set_ylabel('Количество сообщений', fontsize=12)
axes[0].set_title('Распределение длин всех сообщений', fontsize=14, fontweight='bold')
axes[0].legend()
axes[0].grid(axis='y', alpha=0.3)

# Гистограмма 2: сравнение спама и ham
axes[1].hist(df[df['label'] == 'spam']['text_length'], bins=30, alpha=0.7, label='Spam', color='#ff6b6b', edgecolor='black')
axes[1].hist(df[df['label'] == 'ham']['text_length'], bins=30, alpha=0.7, label='Ham', color='#4ecdc4', edgecolor='black')
axes[1].set_xlabel('Длина сообщения (символы)', fontsize=12)
axes[1].set_ylabel('Количество сообщений', fontsize=12)
axes[1].set_title('Сравнение распределения длин (Spam vs Ham)', fontsize=14, fontweight='bold')
axes[1].legend()
axes[1].grid(axis='y', alpha=0.3)

plt.tight_layout()
plt.savefig('/content/text_length_distribution.png', dpi=150, bbox_inches='tight')
print("\n✅ Гистограмма сохранена как: text_length_distribution.png")

# 6. Дополнительно: таблица с интервалами
print("\n" + "="*60)
print("РАСПРЕДЕЛЕНИЕ ПО ИНТЕРВАЛАМ")
print("="*60)

# Создаём интервалы
bins = [0, 20, 40, 60, 80, 100, 200]
labels = ['0-20', '20-40', '40-60', '60-80', '80-100', '100+']

df['length_group'] = pd.cut(df['text_length'], bins=bins, labels=labels, right=False)

# Считаем количество в каждом интервале
length_distribution = df['length_group'].value_counts().sort_index()

print(f"\n{'Интервал (символы)':<20} {'Количество':<15} {'Доля':<10}")
print("-" * 45)
for interval, count in length_distribution.items():
    pct = count / len(df) * 100
    print(f"{interval:<20} {count:<15} {pct:.1f}%")

# 7. Сохраняем статистику в CSV
stats_df = pd.DataFrame({
    'статистика': ['минимум', 'максимум', 'среднее', 'медиана', 'std'],
    'все_сообщения': [
        df['text_length'].min(),
        df['text_length'].max(),
        round(df['text_length'].mean(), 1),
        round(df['text_length'].median(), 1),
        round(df['text_length'].std(), 1)
    ],
    'spam': [
        df[df['label'] == 'spam']['text_length'].min(),
        df[df['label'] == 'spam']['text_length'].max(),
        round(df[df['label'] == 'spam']['text_length'].mean(), 1),
        round(df[df['label'] == 'spam']['text_length'].median(), 1),
        round(df[df['label'] == 'spam']['text_length'].std(), 1)
    ],
    'ham': [
        df[df['label'] == 'ham']['text_length'].min(),
        df[df['label'] == 'ham']['text_length'].max(),
        round(df[df['label'] == 'ham']['text_length'].mean(), 1),
        round(df[df['label'] == 'ham']['text_length'].median(), 1),
        round(df[df['label'] == 'ham']['text_length'].std(), 1)
    ]
})

stats_df.to_csv('/content/text_length_stats.csv', index=False, encoding='utf-8')
print("\n✅ Статистика сохранена как: text_length_stats.csv")

print("\n" + "="*60)
print("ГОТОВО!")
print("="*60)

import re

# 1. Загрузка данных
df = pd.read_csv('/content/spam_balanced.csv', encoding='latin-1')

# 2. Посмотрим, какие колонки есть в файле
print("="*60)
print("КОЛОНКИ В ФАЙЛЕ:")
print("="*60)
print(df.columns.tolist())
print(f"\nПервые 3 строки:")
print(df.head(3))

# 3. Определим, как называются нужные колонки
label_col = None
text_col = None

for col in df.columns:
    if 'v1' in col or 'label' in col.lower():
        label_col = col
    if 'v2' in col or 'message' in col.lower() or 'text' in col.lower():
        text_col = col

print(f"\nНайдена колонка с метками: '{label_col}'")
print(f"Найдена колонка с текстом: '{text_col}'")

# 4. Если колонки найдены - работаем с ними
if label_col and text_col:
    df = df[[label_col, text_col]]
    df.columns = ['label', 'text']

    # 5. Функция очистки текста (для английского языка)
    def clean_text(text):
        text = str(text).lower()                    # Всё в нижний регистр
        text = re.sub(r'[^a-zA-Z\s]', '', text)     # Удаляем всё, кроме английских букв и пробелов
        text = ' '.join(text.split())               # Убираем лишние пробелы
        return text

    # 6. Применяем очистку и ЗАМЕНЯЕМ старую колонку на очищенную
    df['text'] = df['text'].apply(clean_text)

    # 7. Показываем примеры ПОСЛЕ очистки
    print("\n" + "="*60)
    print("ПРИМЕРЫ ОЧИЩЕННОГО ТЕКСТА")
    print("="*60)

    for i in range(min(3, len(df))):
        print(f"\n--- Пример {i+1} ---")
        print(f"Метка: {df['label'].iloc[i]}")
        print(f"Текст: {df['text'].iloc[i][:150]}...")

    # 8. Статистика
    print("\n" + "="*60)
    print("СТАТИСТИКА")
    print("="*60)
    print(f"Всего сообщений: {len(df)}")
    print(f"Средняя длина текста после очистки: {df['text'].str.len().mean():.1f} символов")
    print(f"\nРаспределение классов:")
    print(df['label'].value_counts())

    # 9. Сохраняем в новый CSV-файл (только label и очищенный text)
    output_filename = 'spam_lreg.csv'
    df.to_csv(output_filename, index=False, encoding='utf-8')
    print(f"\nФайл сохранен в Colab как: '{output_filename}'")
    print(f"Полный путь: /content/{output_filename}")
    print(f"Итоговые колонки: {df.columns.tolist()}")

else:
    print("\nНе удалось найти нужные колонки. В файле есть только:")
    print(df.columns.tolist())

print("\n" + "="*60)
print("ОБРАБОТКА ЗАВЕРШЕНА УСПЕШНО!")
print("="*60)

import pandas as pd
import nltk
from nltk.stem import WordNetLemmatizer
from nltk.corpus import wordnet
from nltk import pos_tag, word_tokenize
import re

# 1. Загрузка ВСЕХ необходимых ресурсов NLTK (исправлено)
print("="*60)
print("ЗАГРУЗКА РЕСУРСОВ NLTK")
print("="*60)

# Список всех необходимых ресурсов
resources = [
    'punkt',           # для токенизации (разбиения на слова)
    'punkt_tab',       # НОВЫЙ ресурс, который требуется в последних версиях
    'wordnet',         # для лемматизации (база слов)
    'omw-1.4',         # расширение wordnet для поддержки других языков
    'averaged_perceptron_tagger'  # для определения части речи (POS-тегирования)
]

for resource in resources:
    try:
        nltk.download(resource, quiet=True)
        print(f"✅ Загружено: {resource}")
    except Exception as e:
        print(f"⚠️ Ошибка при загрузке {resource}: {e}")

# Альтернативный способ загрузки всего необходимого одним пакетом (на случай, если по отдельности не сработает)
print("\nПроверка и дозагрузка недостающих ресурсов...")
try:
    nltk.data.find('tokenizers/punkt_tab/english.zip')
except LookupError:
    print("Загрузка punkt_tab через nltk.download('punkt_tab')...")
    nltk.download('punkt_tab')

try:
    nltk.data.find('taggers/averaged_perceptron_tagger.zip')
except LookupError:
    print("Загрузка averaged_perceptron_tagger...")
    nltk.download('averaged_perceptron_tagger')

print("\n✅ Все ресурсы NLTK успешно загружены")

# 2. Загрузка данных
df = pd.read_csv('/content/spam_lreg.csv', encoding='utf-8')

print("\n" + "="*60)
print("ЗАГРУЗКА ДАННЫХ")
print("="*60)
print(f"Размер датасета: {df.shape[0]} строк, {df.shape[1]} столбцов")
print(f"Колонки: {df.columns.tolist()}")

# Проверяем, есть ли колонка 'text'
if 'text' not in df.columns:
    print("❌ Колонка 'text' не найдена!")
    print(f"Доступные колонки: {df.columns.tolist()}")
    exit()

# ==================== ФУНКЦИИ ДЛЯ ЛЕММАТИЗАЦИИ ====================
print("\n" + "="*60)
print("ЛЕММАТИЗАЦИЯ ТЕКСТА")
print("="*60)

def get_wordnet_pos(nltk_tag):
    """Преобразует тег NLTK в тег WordNet для корректной лемматизации"""
    if nltk_tag.startswith('J'):
        return wordnet.ADJ          # Прилагательное
    elif nltk_tag.startswith('V'):
        return wordnet.VERB         # Глагол
    elif nltk_tag.startswith('N'):
        return wordnet.NOUN         # Существительное
    elif nltk_tag.startswith('R'):
        return wordnet.ADV          # Наречие
    else:
        return wordnet.NOUN         # По умолчанию - существительное

def lemmatize_text_with_pos(text):
    """Лемматизирует текст с учётом части речи."""
    if not isinstance(text, str) or len(text.strip()) == 0:
        return ""

    # Токенизация (разбиение на слова)
    try:
        tokens = word_tokenize(text.lower())
    except LookupError:
        # Если токенизатор не работает, используем простой split
        print("⚠️ word_tokenize не работает, используется split()")
        tokens = text.lower().split()

    # POS-тегирование (определение части речи для каждого слова)
    try:
        pos_tags = pos_tag(tokens)
    except LookupError:
        # Если тегирование не работает, лемматизируем все слова как существительные
        lemmatizer = WordNetLemmatizer()
        lemmatized_tokens = [lemmatizer.lemmatize(token, pos=wordnet.NOUN) for token in tokens]
        return ' '.join(lemmatized_tokens)

    # Создаём лемматизатор
    lemmatizer = WordNetLemmatizer()

    # Лемматизируем каждое слово с учётом его части речи
    lemmatized_tokens = []
    for token, pos_tag_word in pos_tags:
        # Получаем часть речи в формате WordNet
        wn_pos = get_wordnet_pos(pos_tag_word)
        # Лемматизируем слово
        lemma = lemmatizer.lemmatize(token, pos=wn_pos)
        lemmatized_tokens.append(lemma)

    # Возвращаем текст, собранный обратно
    return ' '.join(lemmatized_tokens)

# Применяем лемматизацию
print("\nВыполняется лемматизация текстов (может занять некоторое время)...")
df['text_lemmatized'] = df['text'].apply(lemmatize_text_with_pos)
print("✅ Лемматизация завершена")

# ==================== ПРИМЕРЫ ДО И ПОСЛЕ ====================
print("\n" + "="*60)
print("ПРИМЕРЫ ЛЕММАТИЗАЦИИ")
print("="*60)

# Показываем 3 примера
for i in range(min(3, len(df))):
    print(f"\n--- Пример {i+1} ---")
    print(f"ДО лемматизации:     {df['text'].iloc[i][:150]}...")
    print(f"ПОСЛЕ лемматизации:   {df['text_lemmatized'].iloc[i][:150]}...")
    print(f"Метка: {df['label'].iloc[i]}")

# ==================== СТАТИСТИКА ====================
print("\n" + "="*60)
print("СТАТИСТИКА")
print("="*60)

print(f"Всего сообщений: {len(df)}")
print(f"Средняя длина текста ДО лемматизации: {df['text'].str.len().mean():.1f} символов")
print(f"Средняя длина текста ПОСЛЕ лемматизации: {df['text_lemmatized'].str.len().mean():.1f} символов")

# ==================== ЗАМЕНА СТАРОЙ КОЛОНКИ ====================
# Заменяем исходный текст на лемматизированный
df['text'] = df['text_lemmatized']
df = df.drop(columns=['text_lemmatized'])

# ==================== СОХРАНЕНИЕ РЕЗУЛЬТАТА ====================
output_filename = 'spam_lemmatized.csv'
df.to_csv(output_filename, index=False, encoding='utf-8')
print(f"\n✅ Файл сохранен в Colab как: '{output_filename}'")
print(f"📍 Полный путь: /content/{output_filename}")

# Показываем финальный результат
print("\n" + "="*60)
print("ФИНАЛЬНЫЙ РЕЗУЛЬТАТ")
print("="*60)
print(f"Колонки в итоговом датасете: {df.columns.tolist()}")
print(f"\nПервые 3 строки:")
print(df.head(3))

# Инструкция по скачиванию
print("\n" + "="*60)
print("КАК СКАЧАТЬ ФАЙЛ ВРУЧНУЮ:")
print("="*60)
print(f"1. Нажмите на значок папки 📁 в левом меню Colab")
print(f"2. Найдите файл '{output_filename}'")
print("3. Нажмите на три точки справа от файла")
print("4. Выберите 'Download'")

print("\n" + "="*60)
print("ЛЕММАТИЗАЦИЯ ЗАВЕРШЕНА УСПЕШНО!")
print("="*60)

import pandas as pd

# 1. Загружаем исходный (сырой) файл
df_raw = pd.read_csv('/content/spam_balanced.csv', encoding='latin-1')
# Берём первые 2 столбца и переименовываем
df_raw = df_raw.iloc[:, :2]
df_raw.columns = ['label', 'text_raw']

# 2. Загружаем файл ПОСЛЕ ОЧИСТКИ (нижний регистр, удаление пунктуации) - spam_lreg.csv
df_cleaned = pd.read_csv('/content/spam_lreg.csv', encoding='utf-8')
df_cleaned = df_cleaned[['label', 'text']]
df_cleaned.columns = ['label', 'text_cleaned']

# 3. Загружаем файл ПОСЛЕ ЛЕММАТИЗАЦИИ - spam_lemmatized.csv
df_lemmatized = pd.read_csv('/content/spam_lemmatized.csv', encoding='utf-8')
df_lemmatized = df_lemmatized[['label', 'text']]
df_lemmatized.columns = ['label', 'text_lemmatized']

# 4. Объединяем все три датафрейма
# Берём первые 4 строки из исходного для примера
df_sample = df_raw.head(4).copy()
df_sample = df_sample.merge(df_cleaned[['text_cleaned']], left_index=True, right_index=True, how='left')
df_sample = df_sample.merge(df_lemmatized[['text_lemmatized']], left_index=True, right_index=True, how='left')

# 5. Выводим таблицу
print("="*80)
print("ТАБЛИЦА ТРАНСФОРМАЦИИ ТЕКСТА НА РАЗНЫХ ЭТАПАХ ОБРАБОТКИ")
print("="*80)

# Для удобства чтения показываем каждый пример отдельно
for idx, row in df_sample.iterrows():
    print(f"\n--- ПРИМЕР {idx+1} (метка: {row['label']}) ---")
    print(f"{'ПОСЛЕ БАЛАНСИРОВКИ:':<25} {row['text_raw'][:200]}...")
    print(f"{'ПОСЛЕ ОЧИСТКИ:':<25} {row['text_cleaned'][:200]}...")
    print(f"{'ПОСЛЕ ЛЕММАТИЗАЦИИ:':<25} {row['text_lemmatized'][:200]}...")

print(display_df.to_string(index=False))

print("\n" + "="*80)
print("ИСТОЧНИКИ ДАННЫХ ДЛЯ ТАБЛИЦЫ:")
print("="*80)
print(f"📁 spam_balanced.csv            -  файл после балансировки")
print(f"📁 spam_lreg.csv       - после очистки (нижний регистр, удаление пунктуации)")
print(f"📁 spam_lemmatized.csv - после лемматизации (приведение к начальной форме)")

import pandas as pd
import matplotlib.pyplot as plt
from collections import Counter
import seaborn as sns

# 1. Загрузка лемматизированного файла
df = pd.read_csv('/content/spam_lemmatized.csv', encoding='utf-8')

print("="*60)
print("ЗАГРУЗКА ДАННЫХ")
print("="*60)
print(f"Размер датасета: {df.shape[0]} строк, {df.shape[1]} столбцов")
print(f"Колонки: {df.columns.tolist()}")

# Проверяем, есть ли колонка 'text' (лемматизированный текст)
if 'text' not in df.columns:
    print("❌ Колонка 'text' не найдена!")
    exit()

# ==================== ПОДСЧЁТ ЧАСТОТЫ СЛОВ ====================
print("\n" + "="*60)
print("ПОДСЧЁТ ЧАСТОТЫ СЛОВ")
print("="*60)

# Объединяем все лемматизированные тексты в один список слов
all_words = ' '.join(df['text'].astype(str)).split()
total_words = len(all_words)
unique_words = len(set(all_words))

print(f"Всего слов в корпусе: {total_words}")
print(f"Уникальных слов: {unique_words}")
print(f"Средняя частота слова: {total_words/unique_words:.2f}")

# Считаем частоту каждого слова
word_counts = Counter(all_words)

# Выводим топ-10 самых частых слов
print("\n" + "-"*40)
print("ТОП-10 САМЫХ ЧАСТЫХ СЛОВ:")
print("-"*40)
print(f"{'№':<4} {'Слово':<15} {'Частота':<10} {'% от всех слов':<15}")
print("-"*40)

for i, (word, count) in enumerate(word_counts.most_common(10), 1):
    percentage = (count / total_words) * 100
    print(f"{i:<4} {word:<15} {count:<10} {percentage:.2f}%")

# ==================== ВИЗУАЛИЗАЦИЯ ====================
print("\n" + "="*60)
print("ВИЗУАЛИЗАЦИЯ")
print("="*60)

# Настройка стиля
sns.set_style("whitegrid")
plt.rcParams['figure.figsize'] = (12, 6)

# Столбчатая диаграмма для топ-10 слов
top_words = word_counts.most_common(10)
words = [word for word, count in top_words]
counts = [count for word, count in top_words]

fig, axes = plt.subplots(1, 2, figsize=(14, 6))

# Столбчатая диаграмма
colors = plt.cm.viridis(range(len(words)))[::-1]
bars = axes[0].bar(words, counts, color=colors, edgecolor='black', alpha=0.8)
axes[0].set_title('Топ-10 самых частых слов в корпусе', fontsize=14, fontweight='bold')
axes[0].set_xlabel('Слова', fontsize=12)
axes[0].set_ylabel('Частота встречаемости', fontsize=12)
axes[0].tick_params(axis='x', rotation=45)

# Добавляем значения на столбцы
for bar, count in zip(bars, counts):
    axes[0].text(bar.get_x() + bar.get_width()/2, bar.get_height() + 5,
                str(count), ha='center', va='bottom', fontsize=10, fontweight='bold')

# Круговая диаграмма (для топ-10 и "остальные")
top_10_count = sum(counts)
other_count = total_words - top_10_count

pie_data = [top_10_count, other_count]
pie_labels = [f'Топ-10 слов\n({top_10_count} шт.)', f'Остальные слова\n({other_count} шт.)']
pie_colors = ['#ff6b6b', '#4ecdc4']

axes[1].pie(pie_data, labels=pie_labels, autopct='%1.1f%%', colors=pie_colors, startangle=90)
axes[1].set_title('Доля топ-10 слов в общем объёме', fontsize=14, fontweight='bold')

plt.tight_layout()
plt.savefig('/content/word_frequency_top10.png', dpi=150, bbox_inches='tight')
print("\n✅ Диаграмма сохранена как: word_frequency_top10.png")

# ==================== ДЕТАЛИЗАЦИЯ ПО КЛАССАМ ====================
print("\n" + "="*60)
print("АНАЛИЗ ПО КЛАССАМ (SPAM vs HAM)")
print("="*60)

# Разделяем на спам и ham
df_spam = df[df['label'] == 'spam']
df_ham = df[df['label'] == 'ham']

# Считаем частоты для спама
spam_words = ' '.join(df_spam['text'].astype(str)).split()
spam_counts = Counter(spam_words)

# Считаем частоты для ham
ham_words = ' '.join(df_ham['text'].astype(str)).split()
ham_counts = Counter(ham_words)

print("\n--- ТОП-7 слов в СПАМ сообщениях ---")
for i, (word, count) in enumerate(spam_counts.most_common(7), 1):
    print(f"{i}. {word}: {count}")

print("\n--- ТОП-7 слов в HAM сообщениях ---")
for i, (word, count) in enumerate(ham_counts.most_common(7), 1):
    print(f"{i}. {word}: {count}")

# ==================== ДОПОЛНИТЕЛЬНО: ОБЛАКО СЛОВ (опционально) ====================
print("\n" + "="*60)
print("ГЕНЕРАЦИЯ ОБЛАКА СЛОВ")
print("="*60)

try:
    from wordcloud import WordCloud

    # Генерируем облако слов для всего корпуса
    wordcloud = WordCloud(width=800, height=400,
                         background_color='white',
                         colormap='viridis',
                         max_words=100,
                         contour_width=1,
                         contour_color='steelblue').generate_from_frequencies(word_counts)

    plt.figure(figsize=(12, 6))
    plt.imshow(wordcloud, interpolation='bilinear')
    plt.axis('off')
    plt.title('Облако слов (весь корпус)', fontsize=14, fontweight='bold')
    plt.tight_layout()
    plt.savefig('/content/wordcloud_all.png', dpi=150, bbox_inches='tight')
    print("\n✅ Облако слов сохранено как: wordcloud_all.png")

    # Отдельно для спама
    wordcloud_spam = WordCloud(width=800, height=400,
                               background_color='white',
                               colormap='Reds',
                               max_words=100).generate_from_frequencies(spam_counts)

    plt.figure(figsize=(12, 6))
    plt.imshow(wordcloud_spam, interpolation='bilinear')
    plt.axis('off')
    plt.title('Облако слов (СПАМ)', fontsize=14, fontweight='bold', color='darkred')
    plt.tight_layout()
    plt.savefig('/content/wordcloud_spam.png', dpi=150, bbox_inches='tight')
    print("✅ Облако слов (спам) сохранено как: wordcloud_spam.png")

    # Отдельно для ham
    wordcloud_ham = WordCloud(width=800, height=400,
                              background_color='white',
                              colormap='Blues',
                              max_words=100).generate_from_frequencies(ham_counts)

    plt.figure(figsize=(12, 6))
    plt.imshow(wordcloud_ham, interpolation='bilinear')
    plt.axis('off')
    plt.title('Облако слов (HAM)', fontsize=14, fontweight='bold', color='darkblue')
    plt.tight_layout()
    plt.savefig('/content/wordcloud_ham.png', dpi=150, bbox_inches='tight')
    print("✅ Облако слов (ham) сохранено как: wordcloud_ham.png")

except ImportError:
    print("⚠️ Библиотека wordcloud не установлена. Установите её командой: !pip install wordcloud")

# ==================== СОХРАНЕНИЕ РЕЗУЛЬТАТОВ ====================
print("\n" + "="*60)
print("СОХРАНЕНИЕ РЕЗУЛЬТАТОВ")
print("="*60)

# Сохраняем топ-100 слов в CSV
top_100 = word_counts.most_common(100)
top_100_df = pd.DataFrame(top_100, columns=['word', 'frequency'])
top_100_df['percentage'] = (top_100_df['frequency'] / total_words) * 100
top_100_df.to_csv('/content/top_100_words.csv', index=False, encoding='utf-8')
print(f"\n✅ Топ-100 слов сохранён как: top_100_words.csv")

# Сохраняем статистику по классам
class_stats = pd.DataFrame({
    'class': ['spam', 'ham'],
    'total_words': [len(spam_words), len(ham_words)],
    'unique_words': [len(set(spam_words)), len(set(ham_words))],
    'top_word': [spam_counts.most_common(1)[0][0], ham_counts.most_common(1)[0][0]],
    'top_word_freq': [spam_counts.most_common(1)[0][1], ham_counts.most_common(1)[0][1]]
})
class_stats.to_csv('/content/class_statistics.csv', index=False, encoding='utf-8')
print("✅ Статистика по классам сохранена как: class_statistics.csv")

# Вывод списка сохранённых файлов
print("\n" + "="*60)
print("СОХРАНЁННЫЕ ФАЙЛЫ:")
print("="*60)
print("📊 top_100_words.csv      - топ-100 слов с частотами")
print("📊 class_statistics.csv   - статистика по классам spam/ham")
print("📊 word_frequency_top10.png  - столбчатая и круговая диаграммы")
print("📊 wordcloud_all.png      - облако слов для всего корпуса")
print("📊 wordcloud_spam.png     - облако слов для спама")
print("📊 wordcloud_ham.png      - облако слов для ham")

print("\n" + "="*60)
print("КАК СКАЧАТЬ ФАЙЛЫ ВРУЧНУЮ:")
print("="*60)
print("1. Нажмите на значок папки 📁 в левом меню Colab")
print("2. Найдите нужные файлы")
print("3. Нажмите на три точки справа от каждого файла и выберите 'Download'")

print("\n" + "="*60)
print("ОБРАБОТКА ЗАВЕРШЕНА УСПЕШНО!")
print("="*60)

import pandas as pd
import matplotlib.pyplot as plt
from collections import Counter
from nltk.corpus import stopwords
import nltk

# 1. Загрузка данных
df = pd.read_csv('/content/spam_lemmatized.csv', encoding='utf-8')

print("="*60)
print("ЗАГРУЗКА ДАННЫХ")
print("="*60)
print(f"Размер датасета: {df.shape[0]} строк, {df.shape[1]} столбцов")
print(f"Колонки: {df.columns.tolist()}")

# Проверяем, есть ли колонка 'text'
if 'text' not in df.columns:
    print("❌ Колонка 'text' не найдена!")
    exit()

# 2. Загрузка стоп-слов
print("\n" + "="*60)
print("ЗАГРУЗКА СТОП-СЛОВ")
print("="*60)

# Скачиваем список стоп-слов (только если ещё не скачаны)
try:
    nltk.data.find('corpora/stopwords')
except LookupError:
    nltk.download('stopwords', quiet=True)

# Загружаем английские стоп-слова
stop_words = set(stopwords.words('english'))

print(f"Загружено стоп-слов: {len(stop_words)}")
print(f"\nПервые 10 стоп-слов для примера: {list(stop_words)[:10]}")

# 3. Подсчёт частоты слов ДО удаления стоп-слов
print("\n" + "="*60)
print("ТОП-10 СЛОВ ДО УДАЛЕНИЯ СТОП-СЛОВ")
print("="*60)

all_words_before = ' '.join(df['text'].astype(str)).split()
word_counts_before = Counter(all_words_before)

print(f"\n{'№':<4} {'Слово':<15} {'Частота':<10}")
print("-"*30)
for i, (word, count) in enumerate(word_counts_before.most_common(10), 1):
    print(f"{i:<4} {word:<15} {count:<10}")

# 4. Удаление стоп-слов
print("\n" + "="*60)
print("УДАЛЕНИЕ СТОП-СЛОВ")
print("="*60)

def remove_stopwords(text):
    """Удаляет стоп-слова из текста"""
    if not isinstance(text, str):
        return ""
    words = text.split()
    words_filtered = [word for word in words if word not in stop_words]
    return ' '.join(words_filtered)

# Применяем удаление стоп-слов
df['text_no_stopwords'] = df['text'].apply(remove_stopwords)

print("✅ Стоп-слова удалены")

# 5. Показываем примеры ДО и ПОСЛЕ
print("\n" + "="*60)
print("ПРИМЕРЫ ТЕКСТА ДО И ПОСЛЕ УДАЛЕНИЯ СТОП-СЛОВ")
print("="*60)

for i in range(min(3, len(df))):
    print(f"\n--- Пример {i+1} ---")
    print(f"ДО:   {df['text'].iloc[i][:150]}...")
    print(f"ПОСЛЕ:{df['text_no_stopwords'].iloc[i][:150]}...")
    print(f"Удалено слов: {len(df['text'].iloc[i].split()) - len(df['text_no_stopwords'].iloc[i].split())}")

# 6. Подсчёт частоты слов ПОСЛЕ удаления стоп-слов
print("\n" + "="*60)
print("ТОП-10 СЛОВ ПОСЛЕ УДАЛЕНИЯ СТОП-СЛОВ")
print("="*60)

all_words_after = ' '.join(df['text_no_stopwords'].astype(str)).split()
word_counts_after = Counter(all_words_after)

print(f"\n{'№':<4} {'Слово':<15} {'Частота':<10}")
print("-"*30)
for i, (word, count) in enumerate(word_counts_after.most_common(10), 1):
    print(f"{i:<4} {word:<15} {count:<10}")

# 7. Визуализация сравнения
print("\n" + "="*60)
print("ВИЗУАЛИЗАЦИЯ СРАВНЕНИЯ")
print("="*60)

# Подготавливаем данные для графика
top_words_before = word_counts_before.most_common(10)
top_words_after = word_counts_after.most_common(10)

words_before_list = [word for word, count in top_words_before]
counts_before_list = [count for word, count in top_words_before]

words_after_list = [word for word, count in top_words_after]
counts_after_list = [count for word, count in top_words_after]

# Создаём график
fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# График ДО
axes[0].bar(words_before_list, counts_before_list, color='#ff6b6b', edgecolor='black', alpha=0.8)
axes[0].set_title('Топ-10 слов ДО удаления стоп-слов', fontsize=12, fontweight='bold')
axes[0].set_xlabel('Слова', fontsize=10)
axes[0].set_ylabel('Частота', fontsize=10)
axes[0].tick_params(axis='x', rotation=45)

# График ПОСЛЕ
axes[1].bar(words_after_list, counts_after_list, color='#4ecdc4', edgecolor='black', alpha=0.8)
axes[1].set_title('Топ-10 слов ПОСЛЕ удаления стоп-слов', fontsize=12, fontweight='bold')
axes[1].set_xlabel('Слова', fontsize=10)
axes[1].set_ylabel('Частота', fontsize=10)
axes[1].tick_params(axis='x', rotation=45)

plt.tight_layout()
plt.savefig('/content/stopwords_comparison.png', dpi=150, bbox_inches='tight')
print("\n✅ График сравнения сохранён как: stopwords_comparison.png")

# 8. Статистика удаления
print("\n" + "="*60)
print("СТАТИСТИКА УДАЛЕНИЯ СТОП-СЛОВ")
print("="*60)

total_words_before = len(all_words_before)
total_words_after = len(all_words_after)
unique_words_before = len(set(all_words_before))
unique_words_after = len(set(all_words_after))

print(f"Всего слов ДО удаления:   {total_words_before}")
print(f"Всего слов ПОСЛЕ удаления: {total_words_after}")
print(f"Удалено слов:             {total_words_before - total_words_after}")
print(f"Удалено (%):              {(total_words_before - total_words_after) / total_words_before * 100:.2f}%")
print(f"\nУникальных слов ДО:   {unique_words_before}")
print(f"Уникальных слов ПОСЛЕ: {unique_words_after}")

# 9. Какие стоп-слова чаще всего встречались
print("\n" + "="*60)
print("САМЫЕ ЧАСТЫЕ СТОП-СЛОВА В КОРПУСЕ")
print("="*60)

# Находим стоп-слова, которые были удалены
stopwords_found = {}
for word, count in word_counts_before.items():
    if word in stop_words:
        stopwords_found[word] = count

top_stopwords = sorted(stopwords_found.items(), key=lambda x: x[1], reverse=True)[:10]
print(f"\n{'№':<4} {'Стоп-слово':<12} {'Частота':<10}")
print("-"*30)
for i, (word, count) in enumerate(top_stopwords, 1):
    print(f"{i:<4} {word:<12} {count:<10}")

# 10. Заменяем исходный текст на текст без стоп-слов
df['text'] = df['text_no_stopwords']
df = df.drop(columns=['text_no_stopwords'])

# 11. Сохраняем результат
output_filename = 'spam_no_stopwords.csv'
df.to_csv(output_filename, index=False, encoding='utf-8')
print(f"\n✅ Файл без стоп-слов сохранён как: '{output_filename}'")
print(f"📍 Полный путь: /content/{output_filename}")

# 12. Инструкция по скачиванию
print("\n" + "="*60)
print("СОХРАНЁННЫЕ ФАЙЛЫ:")
print("="*60)
print(f"📊 {output_filename}           - датасет без стоп-слов")
print("📊 stopwords_comparison.png     - график сравнения топ-10 слов до/после")

print("\n" + "="*60)
print("КАК СКАЧАТЬ ФАЙЛЫ ВРУЧНУЮ:")
print("="*60)
print("1. Нажмите на значок папки 📁 в левом меню Colab")
print("2. Найдите нужные файлы")
print("3. Нажмите на три точки справа и выберите 'Download'")

print("\n" + "="*60)
print("УДАЛЕНИЕ СТОП-СЛОВ ЗАВЕРШЕНО УСПЕШНО!")
print("="*60)

import pandas as pd
import matplotlib.pyplot as plt
from collections import Counter
import seaborn as sns

# 1. Загрузка лемматизированного файла
df = pd.read_csv('/content/spam_no_stopwords.csv', encoding='utf-8')

print("="*60)
print("ЗАГРУЗКА ДАННЫХ")
print("="*60)
print(f"Размер датасета: {df.shape[0]} строк, {df.shape[1]} столбцов")
print(f"Колонки: {df.columns.tolist()}")

# Проверяем, есть ли колонка 'text' (лемматизированный текст)
if 'text' not in df.columns:
    print("❌ Колонка 'text' не найдена!")
    exit()

# ==================== ПОДСЧЁТ ЧАСТОТЫ СЛОВ ====================
print("\n" + "="*60)
print("ПОДСЧЁТ ЧАСТОТЫ СЛОВ")
print("="*60)

# Объединяем все лемматизированные тексты в один список слов
all_words = ' '.join(df['text'].astype(str)).split()
total_words = len(all_words)
unique_words = len(set(all_words))

print(f"Всего слов в корпусе: {total_words}")
print(f"Уникальных слов: {unique_words}")
print(f"Средняя частота слова: {total_words/unique_words:.2f}")

# Считаем частоту каждого слова
word_counts = Counter(all_words)

# Выводим топ-10 самых частых слов
print("\n" + "-"*40)
print("ТОП-10 САМЫХ ЧАСТЫХ СЛОВ:")
print("-"*40)
print(f"{'№':<4} {'Слово':<15} {'Частота':<10} {'% от всех слов':<15}")
print("-"*40)

for i, (word, count) in enumerate(word_counts.most_common(10), 1):
    percentage = (count / total_words) * 100
    print(f"{i:<4} {word:<15} {count:<10} {percentage:.2f}%")

# ==================== ВИЗУАЛИЗАЦИЯ ====================
print("\n" + "="*60)
print("ВИЗУАЛИЗАЦИЯ")
print("="*60)

# Настройка стиля
sns.set_style("whitegrid")
plt.rcParams['figure.figsize'] = (12, 6)

# Столбчатая диаграмма для топ-10 слов
top_words = word_counts.most_common(10)
words = [word for word, count in top_words]
counts = [count for word, count in top_words]

fig, axes = plt.subplots(1, 2, figsize=(14, 6))

# Столбчатая диаграмма
colors = plt.cm.viridis(range(len(words)))[::-1]
bars = axes[0].bar(words, counts, color=colors, edgecolor='black', alpha=0.8)
axes[0].set_title('Топ-10 самых частых слов в корпусе', fontsize=14, fontweight='bold')
axes[0].set_xlabel('Слова', fontsize=12)
axes[0].set_ylabel('Частота встречаемости', fontsize=12)
axes[0].tick_params(axis='x', rotation=45)

# Добавляем значения на столбцы
for bar, count in zip(bars, counts):
    axes[0].text(bar.get_x() + bar.get_width()/2, bar.get_height() + 5,
                str(count), ha='center', va='bottom', fontsize=10, fontweight='bold')

# Круговая диаграмма (для топ-10 и "остальные")
top_10_count = sum(counts)
other_count = total_words - top_10_count

pie_data = [top_10_count, other_count]
pie_labels = [f'Топ-10 слов\n({top_10_count} шт.)', f'Остальные слова\n({other_count} шт.)']
pie_colors = ['#ff6b6b', '#4ecdc4']

axes[1].pie(pie_data, labels=pie_labels, autopct='%1.1f%%', colors=pie_colors, startangle=90)
axes[1].set_title('Доля топ-10 слов в общем объёме', fontsize=14, fontweight='bold')

plt.tight_layout()
plt.savefig('/content/word_frequency_top101.png', dpi=150, bbox_inches='tight')
print("\n✅ Диаграмма сохранена как: word_frequency_top10.png")

# ==================== ДЕТАЛИЗАЦИЯ ПО КЛАССАМ ====================
print("\n" + "="*60)
print("АНАЛИЗ ПО КЛАССАМ (SPAM vs HAM)")
print("="*60)

# Разделяем на спам и ham
df_spam = df[df['label'] == 'spam']
df_ham = df[df['label'] == 'ham']

# Считаем частоты для спама
spam_words = ' '.join(df_spam['text'].astype(str)).split()
spam_counts = Counter(spam_words)

# Считаем частоты для ham
ham_words = ' '.join(df_ham['text'].astype(str)).split()
ham_counts = Counter(ham_words)

print("\n--- ТОП-7 слов в СПАМ сообщениях ---")
for i, (word, count) in enumerate(spam_counts.most_common(7), 1):
    print(f"{i}. {word}: {count}")

print("\n--- ТОП-7 слов в HAM сообщениях ---")
for i, (word, count) in enumerate(ham_counts.most_common(7), 1):
    print(f"{i}. {word}: {count}")

# ==================== ДОПОЛНИТЕЛЬНО: ОБЛАКО СЛОВ (опционально) ====================
print("\n" + "="*60)
print("ГЕНЕРАЦИЯ ОБЛАКА СЛОВ")
print("="*60)

try:
    from wordcloud import WordCloud

    # Генерируем облако слов для всего корпуса
    wordcloud = WordCloud(width=800, height=400,
                         background_color='white',
                         colormap='viridis',
                         max_words=100,
                         contour_width=1,
                         contour_color='steelblue').generate_from_frequencies(word_counts)

    plt.figure(figsize=(12, 6))
    plt.imshow(wordcloud, interpolation='bilinear')
    plt.axis('off')
    plt.title('Облако слов (весь корпус)', fontsize=14, fontweight='bold')
    plt.tight_layout()
    plt.savefig('/content/wordcloud_all1.png', dpi=150, bbox_inches='tight')
    print("\n✅ Облако слов сохранено как: wordcloud_all.png")

except ImportError:
    print("⚠️ Библиотека wordcloud не установлена. Установите её командой: !pip install wordcloud")

# ==================== СОХРАНЕНИЕ РЕЗУЛЬТАТОВ ====================
print("\n" + "="*60)
print("СОХРАНЕНИЕ РЕЗУЛЬТАТОВ")
print("="*60)

# Сохраняем топ-100 слов в CSV
top_100 = word_counts.most_common(100)
top_100_df = pd.DataFrame(top_100, columns=['word', 'frequency'])
top_100_df['percentage'] = (top_100_df['frequency'] / total_words) * 100
top_100_df.to_csv('/content/top_100_words.csv', index=False, encoding='utf-8')
print(f"\n✅ Топ-100 слов сохранён как: top_100_words.csv")

# Сохраняем статистику по классам
class_stats = pd.DataFrame({
    'class': ['spam', 'ham'],
    'total_words': [len(spam_words), len(ham_words)],
    'unique_words': [len(set(spam_words)), len(set(ham_words))],
    'top_word': [spam_counts.most_common(1)[0][0], ham_counts.most_common(1)[0][0]],
    'top_word_freq': [spam_counts.most_common(1)[0][1], ham_counts.most_common(1)[0][1]]
})
class_stats.to_csv('/content/class_statistics.csv', index=False, encoding='utf-8')
print("✅ Статистика по классам сохранена как: class_statistics.csv")

# Вывод списка сохранённых файлов
print("\n" + "="*60)
print("СОХРАНЁННЫЕ ФАЙЛЫ:")
print("="*60)
print("📊 top_100_words.csv      - топ-100 слов с частотами")
print("📊 class_statistics.csv   - статистика по классам spam/ham")
print("📊 word_frequency_top10.png  - столбчатая и круговая диаграммы")
print("📊 wordcloud_all.png      - облако слов для всего корпуса")
print("📊 wordcloud_spam.png     - облако слов для спама")
print("📊 wordcloud_ham.png      - облако слов для ham")

print("\n" + "="*60)
print("КАК СКАЧАТЬ ФАЙЛЫ ВРУЧНУЮ:")
print("="*60)
print("1. Нажмите на значок папки 📁 в левом меню Colab")
print("2. Найдите нужные файлы")
print("3. Нажмите на три точки справа от каждого файла и выберите 'Download'")

print("\n" + "="*60)
print("ОБРАБОТКА ЗАВЕРШЕНА УСПЕШНО!")
print("="*60)

import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from nltk.corpus import stopwords
import nltk
from scipy.sparse import save_npz
import joblib

# 1. Загрузка данных
df = pd.read_csv('/content/spam_no_stopwords.csv', encoding='utf-8')

print("="*60)
print("ЗАГРУЗКА ДАННЫХ")
print("="*60)
print(f"Размер датасета: {df.shape[0]} строк, {df.shape[1]} столбцов")

# Проверяем и чистим данные
df['text'] = df['text'].fillna('').astype(str)
df = df[df['text'].str.strip() != '']
df = df.reset_index(drop=True)

# 2. Загрузка стоп-слов
print("\n" + "="*60)
print("ЗАГРУЗКА СТОП-СЛОВ")
print("="*60)

try:
    nltk.data.find('corpora/stopwords')
except LookupError:
    nltk.download('stopwords', quiet=True)
stop_words = set(stopwords.words('english'))
print(f"Загружено стоп-слов: {len(stop_words)}")

# 3. Создание и обучение векторайзера TF-IDF
print("\n" + "="*60)
print("TF-IDF ВЕКТОРИЗАЦИЯ")
print("="*60)

vectorizer = TfidfVectorizer(
    max_features=5000,
    stop_words=list(stop_words),
    lowercase=True,
    use_idf=True,
    smooth_idf=True,
    norm='l2'
)

print("Выполняется векторизация...")
tfidf_matrix = vectorizer.fit_transform(df['text'])

print(f"Размер матрицы: {tfidf_matrix.shape}")
print(f"Размер словаря: {len(vectorizer.get_feature_names_out())} слов")

# 4. СОХРАНЕНИЕ СЛОВАРЯ В CSV (КАК БЫЛО РАНЬШЕ)
print("\n" + "="*60)
print("СОХРАНЕНИЕ СЛОВАРЯ В CSV")
print("="*60)

# Получаем слова и их IDF значения
feature_names = vectorizer.get_feature_names_out()
idf_values = vectorizer.idf_

# Создаём DataFrame
feature_df = pd.DataFrame({
    'word': feature_names,
    'idf': idf_values
})

# Сортируем по алфавиту (как в твоей таблице)
feature_df = feature_df.sort_values('word').reset_index(drop=True)

# Сохраняем в CSV
feature_df.to_csv('/content/tfidf_dictionary.csv', index=False, encoding='utf-8')
print("✅ Словарь сохранён как: tfidf_dictionary.csv")
print(f"   Всего слов в словаре: {len(feature_df)}")

# Показываем первые 20 строк (как в твоём примере)
print("\n" + "="*60)
print("ПЕРВЫЕ 20 СТРОК СЛОВАРЯ")
print("="*60)
print(feature_df.head(20).to_string(index=False))

# 5. Дополнительно: сортировка по IDF (редкие слова в начале)
print("\n" + "="*60)
print("ТОП-20 САМЫХ РЕДКИХ СЛОВ (ВЫСОКИЙ IDF)")
print("="*60)

rare_words = feature_df.sort_values('idf', ascending=False)
print(rare_words.head(20).to_string(index=False))

print("\n" + "="*60)
print("ТОП-20 САМЫХ ЧАСТЫХ СЛОВ (НИЗКИЙ IDF)")
print("="*60)

common_words = feature_df.sort_values('idf', ascending=True)
print(common_words.head(20).to_string(index=False))

# 6. Сохраняем также матрицу и векторайзер
print("\n" + "="*60)
print("СОХРАНЕНИЕ МАТРИЦЫ И ВЕКТОРАЙЗЕРА")
print("="*60)

save_npz('/content/tfidf_matrix.npz', tfidf_matrix)
print("✅ Матрица TF-IDF сохранена как: tfidf_matrix.npz")

joblib.dump(vectorizer, '/content/tfidf_vectorizer.pkl')
print("✅ Векторайзер сохранён как: tfidf_vectorizer.pkl")

print("\n" + "="*60)
print("СОХРАНЁННЫЕ ФАЙЛЫ:")
print("="*60)
print("📊 tfidf_dictionary.csv   - словарь (слово → IDF)")
print("📊 tfidf_matrix.npz       - разреженная матрица TF-IDF")
print("📊 tfidf_vectorizer.pkl   - обученный векторайзер")

print("\n" + "="*60)
print("КАК СКАЧАТЬ ФАЙЛЫ ВРУЧНУЮ:")
print("="*60)
print("1. Нажмите на значок папки 📁 в левом меню Colab")
print("2. Найдите нужные файлы")
print("3. Нажмите на три точки справа и выберите 'Download'")

print("\n" + "="*60)
print("ГОТОВО!")
print("="*60)

import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
import pandas as pd
import re
import nltk
from nltk.stem import WordNetLemmatizer
from nltk.corpus import wordnet

# Загружаем ВСЕ необходимые ресурсы NLTK (исправлено)
print("="*60)
print("ЗАГРУЗКА РЕСУРСОВ NLTK")
print("="*60)

# Список всех необходимых ресурсов для новой версии NLTK
resources = [
    'punkt',                        # для токенизации
    'punkt_tab',                    # новый ресурс для токенизации
    'wordnet',                      # для лемматизации
    'omw-1.4',                      # расширение wordnet
    'averaged_perceptron_tagger',   # POS-тегирование (старое название)
    'averaged_perceptron_tagger_eng' # POS-тегирование (новое название)
]

for resource in resources:
    try:
        nltk.download(resource, quiet=True)
        print(f"✅ Загружено: {resource}")
    except Exception as e:
        print(f"⚠️ Ошибка при загрузке {resource}: {e}")

# Альтернативный способ: скачиваем всё необходимое одним пакетом
try:
    nltk.download('punkt', quiet=True)
    nltk.download('averaged_perceptron_tagger', quiet=True)
    nltk.download('wordnet', quiet=True)
    print("\n✅ Базовые ресурсы загружены")
except:
    pass

print("\n✅ Все ресурсы NLTK загружены")

# 1. Загружаем сохранённые данные
print("\n" + "="*60)
print("ЗАГРУЗКА ДАННЫХ")
print("="*60)

from scipy.sparse import load_npz
import joblib

# Загружаем матрицу TF-IDF
tfidf_matrix = load_npz('/content/tfidf_matrix.npz')
print("✅ Матрица TF-IDF загружена")

# Загружаем векторайзер
vectorizer = joblib.load('/content/tfidf_vectorizer.pkl')
print("✅ Векторайзер загружен")

# Загружаем датафрейм с текстами
df = pd.read_csv('/content/spam_no_stopwords.csv', encoding='utf-8')
print("✅ Датафрейм загружен")

# Сбрасываем индексы
df = df.reset_index(drop=True)
print(f"Всего текстов в базе: {len(df)}")

# ==================== ФУНКЦИИ ДЛЯ ОБРАБОТКИ ЗАПРОСА ====================
print("\n" + "="*60)
print("ПОДГОТОВКА ФУНКЦИЙ ОБРАБОТКИ ЗАПРОСА")
print("="*60)

def get_wordnet_pos(nltk_tag):
    """Преобразует тег NLTK в тег WordNet для корректной лемматизации"""
    if nltk_tag.startswith('J'):
        return wordnet.ADJ
    elif nltk_tag.startswith('V'):
        return wordnet.VERB
    elif nltk_tag.startswith('N'):
        return wordnet.NOUN
    elif nltk_tag.startswith('R'):
        return wordnet.ADV
    else:
        return wordnet.NOUN

def clean_query_text(text):
    """Очистка текста запроса (как при обучении)"""
    text = str(text).lower()
    text = re.sub(r'[^a-zA-Z\s]', '', text)
    text = ' '.join(text.split())
    return text

def lemmatize_query_text(text):
    """Лемматизация текста запроса с учётом части речи"""
    if not isinstance(text, str) or len(text.strip()) == 0:
        return ""

    try:
        # Токенизация
        from nltk.tokenize import word_tokenize
        tokens = word_tokenize(text.lower())

        # POS-тегирование
        from nltk import pos_tag
        pos_tags = pos_tag(tokens)

        # Лемматизация
        lemmatizer = WordNetLemmatizer()
        lemmatized_tokens = []
        for token, pos_tag_word in pos_tags:
            wn_pos = get_wordnet_pos(pos_tag_word)
            lemma = lemmatizer.lemmatize(token, pos=wn_pos)
            lemmatized_tokens.append(lemma)

        return ' '.join(lemmatized_tokens)

    except Exception as e:
        # Если POS-тегирование не работает, используем простую лемматизацию
        print(f"⚠️ Ошибка в лемматизации: {e}")
        lemmatizer = WordNetLemmatizer()
        tokens = text.lower().split()
        lemmatized_tokens = [lemmatizer.lemmatize(token, pos=wordnet.NOUN) for token in tokens]
        return ' '.join(lemmatized_tokens)

# Функция поиска
def search_texts(query, vectorizer, tfidf_matrix, texts_df, top_n=3):
    """
    Ищет top_n текстов, наиболее похожих на запрос.
    """
    # Очищаем и лемматизируем запрос
    query_cleaned = clean_query_text(query)
    query_lemmatized = lemmatize_query_text(query_cleaned)

    print(f"  Очищенный запрос: {query_cleaned}")
    print(f"  Лемматизированный запрос: {query_lemmatized}")

    # Векторизуем запрос
    query_vec = vectorizer.transform([query_lemmatized])

    # Считаем косинусное сходство
    similarities = cosine_similarity(query_vec, tfidf_matrix)[0]

    # Находим топ-n индексов
    top_indices = similarities.argsort()[-top_n:][::-1]

    # Формируем результаты
    results = []
    for idx in top_indices:
        results.append({
            'Текст': texts_df.iloc[idx],
            'Похожесть': round(similarities[idx], 6),
            'Метка': df['label'].iloc[idx] if 'label' in df.columns else 'unknown'
        })

    return results

print("✅ Функции поиска готовы")

# ==================== ПРИМЕРЫ ПОИСКА ====================
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

# Функция поиска (упрощённая, без лемматизации, так как тексты уже лемматизированы)
def simple_search(query, vectorizer, tfidf_matrix, texts_df, top_n=3):
    """
    Простой поиск без дополнительной лемматизации
    """
    # Только очистка (нижний регистр, удаление лишних символов)
    import re
    query_cleaned = re.sub(r'[^a-zA-Z\s]', '', query.lower())
    query_cleaned = ' '.join(query_cleaned.split())

    print(f"  Запрос после очистки: '{query_cleaned}'")

    # Векторизуем запрос
    query_vec = vectorizer.transform([query_cleaned])

    # Считаем косинусное сходство
    similarities = cosine_similarity(query_vec, tfidf_matrix)[0]

    # Находим топ-n индексов
    top_indices = similarities.argsort()[-top_n:][::-1]

    # Формируем результаты
    results = []
    for idx in top_indices:
        results.append({
            'Текст': texts_df.iloc[idx],
            'Похожесть': round(similarities[idx], 6),
            'Метка': df['label'].iloc[idx] if 'label' in df.columns else 'unknown'
        })

    return results

print("\n" + "="*60)
print("ТЕСТИРОВАНИЕ ПОИСКА С РАЗНЫМИ ЗАПРОСАМИ")
print("="*60)

# Тест 1: Слово, которое точно есть в словаре
print("\n--- ТЕСТ 1: 'winner' ---")
query_test = "winner"
results = simple_search(query_test, vectorizer, tfidf_matrix, df['text'], top_n=3)
for i, res in enumerate(results, 1):
    print(f"{i}. Похожесть: {res['Похожесть']:.6f} | {res['Метка']}")
    print(f"   {res['Текст'][:100]}...")

# Тест 2: Слово 'call'
print("\n--- ТЕСТ 2: 'call' ---")
query_test = "call"
results = simple_search(query_test, vectorizer, tfidf_matrix, df['text'], top_n=3)
for i, res in enumerate(results, 1):
    print(f"{i}. Похожесть: {res['Похожесть']:.6f} | {res['Метка']}")
    print(f"   {res['Текст'][:100]}...")

# Тест 3: Фраза из слов, которые есть в словаре
print("\n--- ТЕСТ 3: 'free call' ---")
query_test = "free call"
results = simple_search(query_test, vectorizer, tfidf_matrix, df['text'], top_n=3)
for i, res in enumerate(results, 1):
    print(f"{i}. Похожесть: {res['Похожесть']:.6f} | {res['Метка']}")
    print(f"   {res['Текст'][:100]}...")

# Тест 4: Фраза из спам-лексики
print("\n--- ТЕСТ 4: 'winner claim prize' ---")
query_test = "winner claim prize"
results = simple_search(query_test, vectorizer, tfidf_matrix, df['text'], top_n=3)
for i, res in enumerate(results, 1):
    print(f"{i}. Похожесть: {res['Похожесть']:.6f} | {res['Метка']}")
    print(f"   {res['Текст'][:100]}...")

import pandas as pd
from sklearn.model_selection import train_test_split
import os

# 1. Загружаем сбалансированный датасет
df = pd.read_csv('/content/spam_balanced.csv', encoding='utf-8')

print("="*60)
print("РАЗДЕЛЕНИЕ ДАТАСЕТА НА TRAIN/VAL/TEST")
print("="*60)

print(f"Исходный размер датасета: {len(df)} сообщений")
print(f"Распределение классов: spam = {df['label'].value_counts()['spam']}, ham = {df['label'].value_counts()['ham']}")

# 2. Сначала разделяем на train (70%) и временную выборку (30%)
train_df, temp_df = train_test_split(
    df,
    test_size=0.3,           # 30% отложили
    random_state=42,
    stratify=df['label']     # сохраняем пропорцию классов
)

# 3. Временную выборку делим на val (50% от temp = 15% от общего) и test (50% от temp = 15% от общего)
val_df, test_df = train_test_split(
    temp_df,
    test_size=0.5,           # половину от 30% = 15%
    random_state=42,
    stratify=temp_df['label']
)

print(f"\nРазмер обучающей выборки (train): {len(train_df)} сообщений")
print(f"  - spam: {train_df['label'].value_counts()['spam']}")
print(f"  - ham: {train_df['label'].value_counts()['ham']}")

print(f"\nРазмер валидационной выборки (val): {len(val_df)} сообщений")
print(f"  - spam: {val_df['label'].value_counts()['spam']}")
print(f"  - ham: {val_df['label'].value_counts()['ham']}")

print(f"\nРазмер тестовой выборки (test): {len(test_df)} сообщений")
print(f"  - spam: {test_df['label'].value_counts()['spam']}")
print(f"  - ham: {test_df['label'].value_counts()['ham']}")

# 4. Создаём структуру каталогов
os.makedirs('/content/data', exist_ok=True)

# 5. Сохраняем файлы
train_df.to_csv('/content/data/train.csv', index=False, encoding='utf-8')
val_df.to_csv('/content/data/val.csv', index=False, encoding='utf-8')
test_df.to_csv('/content/data/test.csv', index=False, encoding='utf-8')

print("\n✅ Файлы сохранены в папку /content/data/")
print("📁 /content/data/train.csv")
print("📁 /content/data/val.csv")
print("📁 /content/data/test.csv")

# 6. Проверяем, что всё сохранилось
print("\n" + "="*60)
print("ПРОВЕРКА СОХРАНЁННЫХ ФАЙЛОВ")
print("="*60)

for file in ['train.csv', 'val.csv', 'test.csv']:
    df_check = pd.read_csv(f'/content/data/{file}')
    print(f"\n{file}: {len(df_check)} строк, колонки: {df_check.columns.tolist()}")

# Создаём файл метаданных
metadata_content = """# Dataset Card: SMS Spam Classification Dataset

## Источник текстов
Данные взяты из открытого датасета **SMS Spam Collection v.1**, опубликованного на платформе Kaggle:
https://www.kaggle.com/datasets/uciml/sms-spam-collection-dataset

Оригинальный датасет был собран и размечен исследователями:
- Almeida, T.A., Gómez Hidalgo, J.M., Yamakami, A.
  "Contributions to the Study of SMS Spam Filtering: New Collection and Results"
  Proceedings of the 2011 ACM Symposium on Document Engineering (DOCENG'11), 2011.

## Дата формирования
- Сбор данных: 2011 год
- Публикация на UCI: 2012 год
- Публикация на Kaggle: 2 декабря 2016 года
- Обработка для данной работы: май 2026 года

## Структура данных
Датасет содержит SMS-сообщения на английском языке с бинарной разметкой:
- `spam` (спам) — нежелательные рекламные или мошеннические сообщения
- `ham` (легитимные сообщения) — обычная переписка

## Размер выборки
| Выборка | Количество сообщений | Спам | Ham |
|---------|---------------------|------|-----|
| Train   | XXX                  | XXX  | XXX |
| Val     | XXX                  | XXX  | XXX |
| Test    | XXX                  | XXX  | XXX |

*Примечание: точные числа подставятся автоматически*

## Средняя длина текста
| Выборка | Средняя длина (символы) | Средняя длина (слова) |
|---------|------------------------|----------------------|
| Train   | XXX                    | XXX                  |
| Val     | XXX                    | XXX                  |
| Test    | XXX                    | XXX                  |

## Предобработка
Данные прошли следующие этапы очистки:
1. Приведение к нижнему регистру
2. Удаление знаков пунктуации и цифр
3. Удаление PII (email, телефоны, URL, паспортов)
4. Лемматизация с учётом части речи
5. Удаление стоп-слов
6. Балансировка классов (даунсемплинг до 742 сообщений каждого класса)

## Лицензия
CC0 1.0 Universal (Public Domain Dedication)

## Автор обработки
[Твоё имя]
Курсовой проект, [название вуза], 2026
"""

# Вычисляем реальную статистику для вставки в метаданные
print("\n" + "="*60)
print("СТАТИСТИКА ДЛЯ МЕТАДАННЫХ")
print("="*60)

# Считаем среднюю длину текста для каждой выборки
for name, df_set in [('Train', train_df), ('Val', val_df), ('Test', test_df)]:
    avg_len = df_set['text'].str.len().mean()
    avg_words = df_set['text'].str.split().str.len().mean()
    print(f"\n{name}:")
    print(f"  Средняя длина (символы): {avg_len:.1f}")
    print(f"  Средняя длина (слова): {avg_words:.1f}")

# Сохраняем метаданные в файл
with open('/content/data/README.md', 'w', encoding='utf-8') as f:
    f.write(metadata_content)

print("\n✅ Метаданные сохранены как: /content/data/README.md")

# Дополнительно: создаём JSON-вариант метаданных (машиночитаемый)
import json

metadata_json = {
    "dataset_name": "SMS Spam Classification Dataset",
    "source": "Kaggle / UCI - SMS Spam Collection v.1",
    "original_paper": "Almeida et al. (2011)",
    "collection_date": "2011",
    "processing_date": "2026-05",
    "license": "CC0 1.0 Universal",
    "classes": ["spam", "ham"],
    "train_size": len(train_df),
    "val_size": len(val_df),
    "test_size": len(test_df),
    "train_stats": {
        "spam": int(train_df['label'].value_counts()['spam']),
        "ham": int(train_df['label'].value_counts()['ham'])
    },
    "val_stats": {
        "spam": int(val_df['label'].value_counts()['spam']),
        "ham": int(val_df['label'].value_counts()['ham'])
    },
    "test_stats": {
        "spam": int(test_df['label'].value_counts()['spam']),
        "ham": int(test_df['label'].value_counts()['ham'])
    }
}

with open('/content/data/dataset_info.json', 'w', encoding='utf-8') as f:
    json.dump(metadata_json, f, indent=2, ensure_ascii=False)

print("✅ JSON-метаданные сохранены как: /content/data/dataset_info.json")

print("\n" + "="*60)
print("ФИНАЛЬНАЯ СТРУКТУРА КАТАЛОГОВ")
print("="*60)

# Показываем итоговую структуру
!ls -la /content/data/